config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#show'

  resources :units
  resources :lessons


end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :unit
  validates :title, :body, :unit, presence: true

  include RailsSortable::Model
  set_sortable :sort

  scope :top, ->  { where("array_length(lesson_ids, 1) IS NULL") }

  scope :ordered, -> { joins(:unit).order("units.unit_order ASC, sort ASC")}

  before_validation do
    self.lesson_ids = self.lesson_ids.compact
  end

  def lessons
    Lesson.where("? = ANY(lesson_ids)", self.id )
  end

  def full
    [unit.name, title].join(" - ")
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :lessons, -> { order("sort asc") },dependent: :destroy
  validates :name, presence: true

  scope :ordered, -> {order("unit_order asc")}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @units = Unit.all.ordered
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @units = Unit.all.ordered
  end

  def show
    @lesson = Lesson.find params[:id]
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new params.require(:lesson).permit(:unit_id, :title, :body, :lesson_order, :lesson_ids=>[])
    if @lesson.save
      redirect_to lessons_path
    else
      render :new
    end
  end

  def edit
    @lesson = Lesson.find params[:id]
  end

  def update
    @lesson = Lesson.find params[:id]
    if @lesson.update params.require(:lesson).permit(:unit_id, :title, :body, :lesson_order, :lesson_ids=>[])
      redirect_to lessons_path
    else
      render :new
    end
  end

  def destroy
    Lesson.destroy params[:id]
    redirect_to :lessons
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index
    @units = Unit.all.ordered
  end

  def show
  end

  def new
    @unit = Unit.new
  end

  def create
    @unit = Unit.new params.require(:unit).permit(:name, :unit_order)
    if @unit.save
      redirect_to units_path
    else
      render :new
    end
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/dashboard/show.html.erb
<h1>Learn Git</h1>


<% @units.each do |unit| %>
  <h2><%= unit.name %></h2>
  <% unit.lessons.top.each do |lesson| %>
    <%= render lesson %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearnGit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Units", units_path %></li>
      <li><%= link_to "Lessons", lessons_path %></li>
      <li><%= link_to "New Lesson", new_lesson_path %></li>
    </ul>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/lessons/_form.html.erb
<%= simple_form_for @lesson do |f| %>
  <%= f.association :unit, collection: Unit.all.ordered %>
  <%= f.input :title %>
  <%= f.input :lesson_ids, as: :check_boxes, collection: Lesson.ordered, label_method: "full" %>
  <%= f.input :sort %>
  <%= f.input :body %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/lessons/_lesson.html.erb
<h3><%= lesson.title %></h3>
<ul>
<% lesson.lessons.each do |lesson| %>
  <li><%= render lesson %></li>
<% end %>
</ul>

app/views/lessons/edit.html.erb
<h1>Lessons#edit</h1>
<%= render partial: 'form' %>

app/views/lessons/index.html.erb
<div class="page-title">
  <h1>Lessons</h1>
</div>



<% @units.each do |unit| %>
  <h2><%= unit.name %></h2>
  <div class="unit-list sortable">
    <% sortable_fetch(unit.lessons) do |lesson, id_tag| %>
    <div class="unit" id="<%=id_tag%>">
      <div class="">
        <%= lesson.title %>
      </div>
      <div class="">
        <%= link_to "Edit", [:edit, lesson], class: "btn btn-default"  %>
        <%= link_to "Destroy", lesson, method: :delete, class: "btn btn-danger", data: {confirm: "Sure?"} %>
      </div>
    </div>
    <% end %>
  </div>
  <hr>
<% end %>

app/views/lessons/new.html.erb
<h1>Lessons#new</h1>
<%= render partial: 'form' %>

app/views/lessons/show.html.erb
<h1>Lessons#show</h1>
<p>Find me in app/views/lessons/show.html.erb</p>

app/views/units/edit.html.erb
<h1>Units#edit</h1>
<p>Find me in app/views/units/edit.html.erb</p>

app/views/units/index.html.erb
<div class="page-title">
  <h1>Units</h1>
</div>
<div class="well">
  <div class="text-right">
    <%= link_to "New Unit", new_unit_path, class: "btn btn-default" %>
  </div>
</div>

<div class="unit-list">
  <% @units.each do |unit| %>
    <div class="unit">
      <div class="">
        <%= unit.name %>
      </div>
      <div class="">
        <%= unit.unit_order %>
      </div>
      <div class="">
        <%= link_to "Edit", [:edit, unit], class: "btn btn-default" %>
      </div>
    </div>
  <% end %>

</div>

app/views/units/new.html.erb
<h1>Units#new</h1>
<%= simple_form_for @unit do |f| %>
  <%= f.input :name %>
  <%= f.input :unit_order %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/units/show.html.erb
<h1>Units#show</h1>
<p>Find me in app/views/units/show.html.erb</p>